apiVersion: v1
kind: Pod
metadata:
  name: activity1
  labels:
    env: dev
    app: nop
    purpose: understanding
spec:
  containers:
    - name: nopcommerce
      image: shaikkhajaibraim/nopcommercejune2024:070624
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          memory: "250Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "500m"