apiVersion: v1
kind: Pod
metadata: 
  name: activity2
  labels:
    env: dev
    app: spc 
    purpose: test
spec: 
  containers:
    - name: activity2
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: "TCP"
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"